AprendeAyudando/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.index, name='index'), # /courses/
    path('inscription/<int:course_id>/', views.inscription, name='inscription'), # /courses/inscription/1/
    path('<int:course_id>/', views.join, name='join'), # /courses/curso/1
    path('leave/<int:course_id>/', views.leave, name='leave'), # /courses/leave/1/
    path('create/', views.createCourse, name='create'),
    path('update/<int:course_id>', views.update, name='update'),
    path('enrolled/', views.enrolled, name='enrolled'),
    path('delete/<int:course_id>/', views.delete, name='delete'), # /courses/delete/1/
    path('users/<int:course_id>/', views.users, name='users'), # /courses/users/1/
    path('removeUser/<int:course_id>/<int:user_id>/', views.removeUser, name='removeUser'),
    path('banned/<int:course_id>/', views.banned, name='banned'), # /courses/users/1/ 
]

AprendeAyudando/news/urls.py
from django.urls import path
from . import views
from news.views import (NewsList, NewsCreate, NewsDetail, NewsUpdate, NewsDelete)


app_name = 'news'
urlpatterns = [
    path('', NewsList.as_view(), name='news-list'),
    path('news/add/', NewsCreate.as_view(), name='news-add'),
    path('news/<int:pk>/update/', NewsUpdate.as_view(), name='news-update'),
    path('news/<int:pk>/delete/', NewsDelete.as_view(), name='news-delete'),
    path('news/<int:pk>/', NewsDetail.as_view(), name='news-detail'),
]

AprendeAyudando/quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'
urlpatterns = [
    path('create/<str:courseOrActivity>/<int:courseOrActivity_id>/', views.createQuiz, name='createQuiz'),
    path('create/questions/<int:quiz_id>/<int:number_questions>/', views.createQuestions, name='createQuestions'),
    path('create/answers/<int:question_id>/<int:number_questions>/<int:number_answers>/', views.createAnswers, name='createAnswers'),
    path('startquiz/<int:quiz_id>/',views.startQuiz, name='startQuiz'),
    path('doquiz/<int:quiz_id>/', views.doQuiz, name='doQuiz'),
    path('doquiz/questionasked/<int:question_id>/', views.doQuizQuestionAsked, name='doQuizQuestionAsked'),
    path('deletequiz/<int:quiz_id>/', views.deleteQuiz, name='deleteQuiz'),
    path('administrationquiz/<int:quiz_id>/', views.administrationQuiz, name='administrationQuiz'),
    path('deletequestion/<int:question_id>/', views.deleteQuestion, name='deleteQuestion'),
    path('updatequestion/<int:question_id>/', views.updateQuestion, name='updateQuestion'),
    path('updateanswers/<int:question_id>/<int:number_answers>/', views.updateAnswers, name='updateAnswers'),
    path('updatequiz/<int:quiz_id>/', views.updateQuiz, name='updateQuiz'),
    path('viewqualifications/<int:quiz_id>/', views.viewQualifications, name='viewQualifications'),
]

AprendeAyudando/resources/urls.py
from django.urls import path
from . import views

app_name = 'resources'
urlpatterns = [
    path('create/<str:courseOrActivity>/<int:activityCourseFk>', views.createResource, name='createResource'), # /resource/create/1/
    path('delete/<int:resource_id>/', views.delete, name='delete'), # /resource/delete/1/
]

AprendeAyudando/review/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'review'
urlpatterns = [
    path('create/<int:id_enrollable>/<str:title_enrollable>/', views.create, name='create'),
    path('list/<int:id_enrollable>/<str:title_enrollable>/<str:activityOrCourse>', views.list, name='list'),
    path('details/<int:id_review>/<str:title_enrollable>/', views.details, name='details'),
]

AprendeAyudando/urls.py
from django.contrib import admin
from django.urls import include, path

from django.contrib.auth import views as auth_views
from django.conf.urls import url

from . import views

urlpatterns = [
    path('', views.landingpage),

    url('register/', views.user_register, name='user_register'),
    url('account/', views.account, name='account'),
    url('accountdelete/', views.delete_account, name='account_delete'),
    
    path('accounts/', include('django.contrib.auth.urls')),
        # accounts/login/ [name='login']
        # accounts/logout/ [name='logout']
        # accounts/password_change/ [name='password_change']
        # accounts/password_change/done/ [name='password_change_done']
        # accounts/password_reset/ [name='password_reset']
        # accounts/password_reset/done/ [name='password_reset_done']
        # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
        # accounts/reset/done/ [name='password_reset_complete']
    
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path('courses/', include('courses.urls')),
    path('activity/', include('activity.urls')),
    path('requestpermissions/', include('request_permissions.urls')),
]

admin.site.site_header = 'Administración Aprende Ayudando'
admin.site.index_title = 'Administración'
admin.site.site_title = 'Aprende Ayudando'

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.index, name='index'), # /courses/
    path('inscription/<int:course_id>/', views.inscription, name='inscription'), # /courses/inscription/1/
    path('<int:course_id>/', views.join, name='join'), # /courses/curso/1
    path('leave/<int:course_id>/', views.leave, name='leave'), # /courses/leave/1/
    path('create/', views.createCourse, name='create'),
    path('enrolled/', views.enrolled, name='enrolled'),

    path('createResource/<int:course_id>', views.createResource, name='createResource'),
]

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns = [
    path('create/<int:activityCourseFk>', views.createForum, name='create'),
    path('<int:forum_id>/', views.join, name='join'), # /forum/1
    path('delete/<int:forum_id>/', views.delete, name='delete'), # /forum/delete/1/

]

AprendeAyudando/AprendeAyudando/forms.py
from django import forms
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm

class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

class RecoverForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))

class UploadForm(forms.ModelForm):
    username = forms.CharField(disabled=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}), required=False)
    password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}), required=False)
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'password_repeat', 'first_name', 'last_name']

AprendeAyudando/AprendeAyudando/views.py
from django.shortcuts import render
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth import login, logout
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.core.mail import send_mail, EmailMultiAlternatives
from django.conf import settings
from .forms import RegisterForm, RecoverForm, UploadForm
import random
import string

def has_group(user, group_name):
    group = Group.objects.get(name=group_name)
    return True if group in user.groups.all() else False

def landingpage(request):
    grupo = 'Invitado'
    if request.user.has_perm('courses.view_course'):
        grupo = 'Estudiante'
    if request.user.has_perm('courses.add_course'):
        grupo = 'Profesor'
    if request.user.has_perm('activity.add_activity'):
        grupo = 'Entidad'

    context = {
        'grupo': grupo
    }
    return render(request, 'landingpage/index.html', context)

def news(request):
    return render(request, 'news/index.html')

@login_required
def account(request):
    return render(request, 'landingpage/account.html')

@login_required
def delete_account(request):
    if request.method == 'POST':
        if "cancel" in request.POST:
            return redirect('/account')
        else:
            request.user.delete()
            return redirect('/')

    return render(request, 'landingpage/delete_account.html')
    
def user_register(request):
    # if this is a POST request we need to process the form data
    template = 'registration/register.html'
   
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'El nombre de usuario ya existe.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'El correo electrónico ya existe.'
                })
            elif form.cleaned_data['password'] != form.cleaned_data['password_repeat']:
                return render(request, template, {
                    'form': form,
                    'error_message': 'Las contraseñas no coinciden.'
                })
            else:
                # Create the user:
                user = User.objects.create_user(
                    form.cleaned_data['username'],
                    form.cleaned_data['email'],
                    form.cleaned_data['password']
                )
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.save()
               
                # add role 'student' to new user
                studentGroup = Group.objects.get(name='Estudiante')
                studentGroup.user_set.add(user)

                # log the user in
                login(request, user)
               
                # redirect to accounts page
                return HttpResponseRedirect(reverse('account'))

   # No post data availabe, let's just show the page.
    else:
        form = RegisterForm()

    return render(request, template, {'form': form})

def recoverpassword(request):
    # if this is a POST request we need to process the form data
    template = 'registration/recoverpassword.html'
   
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        miForm = RecoverForm(request.POST)
        # check whether it's valid:
        if miForm.is_valid():
            if User.objects.filter(email=miForm.cleaned_data['email']).exists():
                # Minuto 19:19
                infForm=miForm.cleaned_data

                size = 12
                chars = string.ascii_uppercase+string.ascii_lowercase+string.digits

                newPass = ''.join(random.choice(chars) for x in range(size))
                
                user = User.objects.get(email=infForm['email'])
                user.set_password(newPass)
                user.save()

                subject = 'Solicitud de nueva contraseña'
                email_from = settings.EMAIL_HOST_USER 
                email_to = [infForm['email']]
                text_content = "ERROR"
                html_content = """  <table style="max-width: 600px; text-align: center; padding: 10px; margin:0 auto; border-collapse: collapse;">
                                        <tr>
                                            <td style="background-color: #ecf0f1; text-align: center; padding: 0">
                                                <a href="http://127.0.0.1:8000/">
                                                    <img width="20%" style="display:block; margin: 1.5% 3%; text-align: center;" src="https://aprendeayudando.herokuapp.com/static/general/images/logoTransparent.png">
                                                </a>
                                            </td>
                                        </tr>
                                        
                                        <tr>
                                            <td style="background-color: #ecf0f1">
                                                <div style="color: #34495e; margin: 4% 10% 2%; text-align: center;font-family: sans-serif">
                                                    <h2 style="color: #ff7d97; margin: 0 0 7px">¿Ha olvidado su contraseña?</h2>
                                                    <p style="margin: 2px; font-size: 15px">""" +  "Buenas, %s %s</p>" %(user.first_name, user.last_name) + """<p style="margin: 2px; font-size: 15px">
                                                        Ha solicitado una nueva contraseña en la plataforma AprendeAyudando, su nueva contraseña es: <strong>""" + "%s" %newPass + """</strong></p>
                                                    <br>
                                                    <div style="width: 100%; text-align: center">
                                                        <a style="text-decoration: none; border-radius: 5px; padding: 11px 23px; color: white; background-color: #3498db" href="http://127.0.0.1:8000/accounts/login/">Iniciar Sesión</a>	
                                                    </div>
                                                    <p style="color: #b3b3b3; font-size: 12px; text-align: center;margin: 30px 0 0">AprendeAyudando 2021</p>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>"""

                msg = EmailMultiAlternatives(subject, text_content, email_from, email_to)
                msg.attach_alternative(html_content, "text/html")
                msg.send()
                
                return render(request, template, {
                    'form': miForm,
                    'message': 'La nueva contraseña ha sido enviada a su correo electrónico.'
                })
            else:
                return render(request, template, {
                    'form': miForm,
                    'error_message': 'Inténtelo de nuevo. El correo electrónico no existe.'
                })
            

   # No post data availabe, let's just show the page.
    else:
        miForm = RecoverForm()

    return render(request, template, {'form': miForm})

@login_required
def modify(request, username):
    template = 'registration/modify.html'
    user = User.objects.get(username=username)
    if not request.user == user:
        return HttpResponseForbidden()
    modForm = UploadForm(instance=user)
    return render(request, template, {'form': modForm, 'username':username})

@login_required
def update(request, username):
    template = 'registration/modify.html'
    user = User.objects.get(username=username)
    userEmail = user.email
    modForm = UploadForm(request.POST, instance=user)
    if request.method == 'POST':
        if modForm.is_valid():

            infForm=modForm.cleaned_data
            email = infForm['email']
            password = infForm['password']
            confpassword = infForm['password_repeat']
            firstName = infForm['first_name']
            lastName = infForm['last_name']

            if User.objects.filter(email=email).exists() and userEmail != email:
                    return render(request, template, {
                        'form': modForm,
                        'error_message': 'El correo electrónico ya existe.'
                    })
            elif password != confpassword:
                    return render(request, template, {
                        'form': modForm,
                        'error_message': 'Las contraseñas no coinciden.'
                    })
            else:
                
                user.email = email
                user.first_name = firstName
                user.last_name = lastName
                
                if password != "":
                    user.set_password(password)
                    user.save()

                    subject = 'Cambio de contraseña'
                    email_from = settings.EMAIL_HOST_USER 
                    email_to = [infForm['email']]
                    text_content = "ERROR"
                    html_content = """  <table style="max-width: 600px; text-align: center; padding: 10px; margin:0 auto; border-collapse: collapse;">
                                            <tr>

AprendeAyudando/AprendeAyudando/templates/courses/curso.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Curso{% endblock %}

{% block style %}
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'courses/style.css' %}">
{% endblock %}
    
{% block content %}
{% load auth_extras %}
<section class="bg-light text-dark py-5 min-vh-100">
    
    <div class="container py-2">
<!-- DESCRIPCION -->
        <div class="shadow p-3 mb-5 bg-white rounded">
            <div class="row">
                <div class="col-12">
                    <h1 class="border-bottom">{{ course.title }}</h1>
                </div>
                <div class="col-12 py-1">
                    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                </div>
                <div class="col-6">
                    {% if isOwner %}
                        <p>Bienvenido a tu curso: <strong>{{ course.title }}</strong></p>
                    {% else %}
                        <p>Hola {{ usuario.first_name }}! Te encuentras en el curso: <strong>{{ course.title }}</strong> del profesor <strong>{{ course.teacher.first_name }}</strong></p>
                    {% endif %}
                </div>
                <div class="col-6 text-right">
                    {% if show_de_enroll %}
                        <form action="{% url 'courses:leave' course.id %}" method="post">
                            {% csrf_token %}
                            <input type="submit" class="mr-2 btn btn-danger btn-sm" value="Desmatricularse">
                        </form>
                    {% endif %}
                </div>
                <div class="col-12">
                    <p>{{course.description}}</p>
                </div>    
            </div>
            <br>
<!-- FOROS -->
            <div class="shadow-none p-3 mb-3 bg-light rounded">
                <div class="row">
                    <div class="col-6">
                        <h4 data-toggle="collapse" role="button" aria-expanded="true" aria-controls="forosAccordion" href="#forosAccordion" class="border-bottom">Foros</h4>
                    </div>
                    <div class="col-6 text-right">
                        {% if isOwner or user.is_superuser %}
                            <a  href="{% url 'forum:create' courseOrActivity course.id %}" class="col-lg-3 btn btn-secondary btn-sm">Crear un foro</a>
                        {% endif %}
                    </div>
                    <div class="col-12 collapse show" id="forosAccordion">
                        {% if forumListCourse %}
                            <ol id="prettyList">
                                {% for forum in forumListCourse %}
                                    <li id="prettyListItem"><a href="{% url 'forum:join' forum.id %}">{{ forum.title }}</a></li>
                                {% endfor %}
                            </ol>
                        {% else %}
                            <p>Lo sentimos, no hay foros disponibles.</p>
                        {% endif %}
                    </div> 
                </div>
            </div>
        
<!-- RECURSOS -->
            <div class="shadow-none p-3 mb-3 bg-light rounded">
                <div class="row">
                    <div class="col-6">
                        <h4 data-toggle="collapse" role="button" aria-expanded="true" aria-controls="recursosAccordion" href="#recursosAccordion" class="border-bottom">Recursos</h4>
                    </div>
                    <div class="col-6 text-right">
                        {% if isOwner or user.is_superuser %}
                            <a href="{% url 'resources:createResource' courseOrActivity course.id %}" class="col-lg-3 btn btn-secondary btn-sm">Crear un recurso</a>
                        {% endif %}
                    </div> 
                    <div class="col-12 collapse show" id="recursosAccordion">
                        {% if resourceListCourse %}
                            <ol id="prettyList">
                                {% for resource in resourceListCourse %}
                                    <li id="prettyListItem">
                                        {% if resource.isLocalFile %} 
                                            <a href="{{ resource.file.url }}" target="_blank">{{ resource.resourceText }}</a>
                                        {% else %}
                                            <a href="{{ resource.resourceLink }}" target="_blank">{{ resource.resourceText }}</a>
                                        {% endif %}

                                            {% if isOwner or user.is_superuser %}
                                                <a class="btn btn-sm rounded-circle btn-danger" href="{% url 'resources:delete' resource.id %}">X</a>
                                            {% endif %}
                                    </li>
                                {% endfor %}
                            </ol>
                        {% else %}
                            <p>Lo sentimos, no hay recusos disponibles.</p>
                        {% endif %}
                    </div> 
                </div>
            </div>
                
    <!-- Test -->
            <div class="shadow-none p-3 mb-5 bg-light rounded">
                <div class="row">
                    <div class="col-6">
                        <h4 data-toggle="collapse" role="button" aria-expanded="true" aria-controls="testAccordion" href="#testAccordion" class="border-bottom">Tests</h4>
                    </div>
                    <div class="col-6 text-right">
                        {% if isOwner or user.is_superuser %}
                            <a href="{% url 'quiz:createQuiz' courseOrActivity course.id %}" class="col-lg-3 btn btn-secondary btn-sm">Crear un Test</a>
                        {% endif %}
                    </div>
                    {% if quizListCourse %} 
                        <div class="quizElements" class="col-12 collapse hidden" id="testAccordion">
                            {% for quiz in quizListCourse %}
                                <a href="{% url 'quiz:startQuiz' quiz.id %}" class="quizElements">
                                    <div class="card">
                                        <div class="card-text">
                                            {% if quiz.maximum_date is not None %}
                                                <span class="date">Fecha límite: {{quiz.maximum_date}}</span>
                                            {% else %}
                                                <span class="date">Sin fecha límite</span>
                                            {% endif %}
                                            <h2 class="clearh2">{{ quiz.title }}</h2>
                                            <p>{{ quiz.description }}</p>
                                            
                                        </div>
                                        {% with list_info=dic_test|get_item_from_index:quiz.id %}
                                            <div class="card-stats">
                                                <div class="stat">
                                                    <div class="value">{{list_info|get_item_from_index:0}}</div>
                                                    <div class="type">Intentos</div>
                                                </div>
                                                <div class="stat border">
                                                    <div class="value">
                                                        {% if list_info|get_item_from_index:1 is None %}
                                                            -
                                                        {% else %}
                                                            {{list_info|get_item_from_index:1}}
                                                        {% endif %}
                                                    </div>
                                                    <div class="type">Calificación</div>
                                                </div>
                                                <div class="stat">
                                                    <div class="value">
                                                        {% if list_info|get_item_from_index:2 is None %}
                                                            -
                                                        {% else %}
                                                            {{list_info|get_item_from_index:2}}
                                                        {% endif %}
                                                    </div>
                                                    <div class="type">Acertadas</div>
                                                </div>
                                            </div>
                                        {% endwith %}
                                    </div>
                                </a>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div class="col-12"  class="col-12 collapse hidden" id="testAccordion">
                            <p>Lo sentimos, no hay tests disponibles.</p>
                        </div>
                    {% endif %}
                </div>
            </div>

    <!-- ENCUESTAS DE SATISFACCIÓN -->
            <div class="row py-2 text-center">
                {% if not isOwner and show_review %}
                    <div class="col-12">
                        <a href="{% url 'review:create' course.id course.title %}" class="btn btn-success btn-sm">Puntuar este curso</a>
                    </div>
                {% endif %}
            </div>

    <!-- TEST Y BORRADO (SOLO DUEÑO Y ADMIN) -->
            <div class="row py-2">
                {% if isOwner or user.is_superuser %}
                    <a href="{% url 'courses:delete' course.id %}" class="ml-4 mr-2 btn btn-danger btn-sm">Borrar curso</a>
                    <a href="{% url 'courses:update' course.id %}" class=" mr-2 btn btn-warning btn-sm">Modificar curso</a>
                    <a href="{% url 'courses:users' course.id %}" class="mr-2 btn btn-info btn-sm">Ver usuarios matriculados</a>
                    <a href="{% url 'review:list' course.id course.title 'Course' %}" class="mr-2 btn btn-info btn-sm">Ver encuestas de satisfacción</a>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

AprendeAyudando/AprendeAyudando/templates/courses/deleteCourse.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Borrar Curso{% endblock %}

{% block content %}
<section class="bg-white text-dark py-5 min-vh-100">
    <div class="container py-5 text-center">
        <img class="rounded-circle" src="/static/general/images/warning.png" alt="Warning icon" width="140" height="140">
        <h1>¿Estás seguro que quieres borrar el curso?</h1>
        <h3>Se borrará también toda la información asociada a él.</h3>
        <form class="text-center" action="{% url 'courses:delete' course.id %}" method="POST">
            {% csrf_token %}
            <a class="btn btn-outline-dark btn-lg mx-2" href="{% url 'courses:join' course.id %}">Cancelar</a>
            <input type="submit" value="Confirmar" class="btn btn-danger btn-lg">
        </form>
    </div>
</section>

{% endblock %}

AprendeAyudando/AprendeAyudando/templates/courses/index.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Cursos {% endblock %}

{% block content %}
<section class="bg-white text-dark py-5 min-vh-100">
    {% load static %}
    {% load auth_extras %}
    <link rel="stylesheet" type="text/css" href="{% static 'courses/style.css' %}">

    <div class="container py-5">
        <div class="row">
            <div class="col-4 ml-auto mb-4"> 
                {% if filtered_by_enrolled %}
                    <h1>Tus cursos</h1>
                {% else %}
                    <h1>Cursos disponibles</h>
                {% endif %}
            </div>
            <div class="col-8 mr-auto mb-4 text-right"> 
                {% if is_teacher %}
                    <a href="{% url 'courses:create' %}" class="btn btn-secondary">Añadir curso</a>
                {% elif user|has_group:"EntidadPublicoPrivada" %}
                    <p>Aviso: Necesitas ser Estudiante para poder acceder a la información de los cursos.</p>
                {% elif user|is_guest %}
                    <p>Aviso: Necesitas registrarte para poder acceder a la información de los cursos.</p>
                {% endif %}
            </div>
            <div class="col-12">
                {% if courseList %}
                <ol id="prettyList"><strong>
                    {% for course in courseList %}
                        {% if user|is_owner:course.teacher or user|has_group:"Estudiante" or user.is_superuser %}
                            <li id="prettyListItem"><a href="{% url 'courses:join' course.id %}">{{ course.title }}</a></li>
                        {% else %}
                            <li id="prettyListItem"><span style="color:#818181;">{{ course.title }}</span></li>
                        {% endif %}
                    {% endfor %}
                </strong></ol>
                {% else %}
                    <p>Lo sentimos, no hay cursos disponibles.</p>
                {% endif %}
            </div> 
        </div> 
    </div>
</section>
{% endblock %}