AprendeAyudando/news/urls.py
from django.urls import path
from . import views
from news.views import (NewsList, NewsCreate, NewsDetail, NewsUpdate, NewsDelete)


app_name = 'news'
urlpatterns = [
    path('', NewsList.as_view(), name='news-list'),
    path('news/add/', NewsCreate.as_view(), name='news-add'),
    path('news/<int:pk>/update/', NewsUpdate.as_view(), name='news-update'),
    path('news/<int:pk>/delete/', NewsDelete.as_view(), name='news-delete'),
    path('news/<int:pk>/', NewsDetail.as_view(), name='news-detail'),
]

AprendeAyudando/urls.py
from django.contrib import admin
from django.urls import include, path

from django.contrib.auth import views as auth_views
from django.conf.urls import url

from . import views

urlpatterns = [
    path('', views.landingpage),

    url('register/', views.user_register, name='user_register'),
    url('account/', views.account, name='account'),
    url('accountdelete/', views.delete_account, name='account_delete'),
    
    path('accounts/', include('django.contrib.auth.urls')),
        # accounts/login/ [name='login']
        # accounts/logout/ [name='logout']
        # accounts/password_change/ [name='password_change']
        # accounts/password_change/done/ [name='password_change_done']
        # accounts/password_reset/ [name='password_reset']
        # accounts/password_reset/done/ [name='password_reset_done']
        # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
        # accounts/reset/done/ [name='password_reset_complete']
    
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path('courses/', include('courses.urls')),
    path('activity/', include('activity.urls')),
    path('requestpermissions/', include('request_permissions.urls')),
]

admin.site.site_header = 'Administración Aprende Ayudando'
admin.site.index_title = 'Administración'
admin.site.site_title = 'Aprende Ayudando'

activity/urls.py
from django.urls import path
from . import views

app_name = 'activity'
urlpatterns = [
    path('', views.index, name='index'), # /activity/
    path('inscription/<int:activity_id>/', views.inscription, name='inscription'), # /activity/inscripcion/1/
    path('<int:activity_id>/', views.join, name='join'), # /activity/curso/1
    path('leave/<int:activity_id>/', views.leave, name='leave'), # /activity/leave/1/
    path('create/', views.createActivity, name='create'),
    path('enrolled/', views.enrolled, name='enrolled'),
    path('<int:activity_id>/activityrequest/', views.view_activity_request, name='activityrequest'),
    path('<int:activity_id>/action_activity_request/', views.action_activity_request, name='action_activity_request'),
]

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns = [
    path('create/<int:activityCourseFk>', views.createForum, name='create'),
    path('<int:forum_id>/', views.join, name='join'), # /forum/1
    path('delete/<int:forum_id>/', views.delete, name='delete'), # /forum/delete/1/

]

AprendeAyudando/forms.py
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

AprendeAyudando/news/forms.py
from django import forms
from .models import News
from django.forms import Textarea

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['headline', 'content']
        widgets = {
            'headline': forms.TextInput(attrs={'class':'form-control'}),
            'content': Textarea(attrs={'class':'form-control'})
        }

AprendeAyudando/AprendeAyudando/views.py
from django.shortcuts import render
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth import login, logout
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.core.mail import send_mail, EmailMultiAlternatives
from django.conf import settings
from .forms import RegisterForm, RecoverForm, UploadForm
import random
import string

def has_group(user, group_name):
    group = Group.objects.get(name=group_name)
    return True if group in user.groups.all() else False

def landingpage(request):
    grupo = 'Invitado'
    if request.user.has_perm('courses.view_course'):
        grupo = 'Estudiante'
    if request.user.has_perm('courses.add_course'):
        grupo = 'Profesor'
    if request.user.has_perm('activity.add_activity'):
        grupo = 'Entidad'

    context = {
        'grupo': grupo
    }
    return render(request, 'landingpage/index.html', context)

def news(request):
    return render(request, 'news/index.html')

@login_required
def account(request):
    return render(request, 'landingpage/account.html')

@login_required
def delete_account(request):
    if request.method == 'POST':
        if "cancel" in request.POST:
            return redirect('/account')
        else:
            request.user.delete()
            return redirect('/')

    return render(request, 'landingpage/delete_account.html')
    
def user_register(request):
    # if this is a POST request we need to process the form data
    template = 'registration/register.html'
   
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'El nombre de usuario ya existe.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'El correo electrónico ya existe.'
                })
            elif form.cleaned_data['password'] != form.cleaned_data['password_repeat']:
                return render(request, template, {
                    'form': form,
                    'error_message': 'Las contraseñas no coinciden.'
                })
            else:
                # Create the user:
                user = User.objects.create_user(
                    form.cleaned_data['username'],
                    form.cleaned_data['email'],
                    form.cleaned_data['password']
                )
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.save()
               
                # add role 'student' to new user
                studentGroup = Group.objects.get(name='Estudiante')
                studentGroup.user_set.add(user)

                # log the user in
                login(request, user)
               
                # redirect to accounts page
                return HttpResponseRedirect(reverse('account'))

   # No post data availabe, let's just show the page.
    else:
        form = RegisterForm()

    return render(request, template, {'form': form})

def recoverpassword(request):
    # if this is a POST request we need to process the form data
    template = 'registration/recoverpassword.html'
   
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        miForm = RecoverForm(request.POST)
        # check whether it's valid:
        if miForm.is_valid():
            if User.objects.filter(email=miForm.cleaned_data['email']).exists():
                # Minuto 19:19
                infForm=miForm.cleaned_data

                size = 12
                chars = string.ascii_uppercase+string.ascii_lowercase+string.digits

                newPass = ''.join(random.choice(chars) for x in range(size))
                
                user = User.objects.get(email=infForm['email'])
                user.set_password(newPass)
                user.save()

                subject = 'Solicitud de nueva contraseña'
                email_from = settings.EMAIL_HOST_USER 
                email_to = [infForm['email']]
                text_content = "ERROR"
                html_content = """  <table style="max-width: 600px; text-align: center; padding: 10px; margin:0 auto; border-collapse: collapse;">
                                        <tr>
                                            <td style="background-color: #ecf0f1; text-align: center; padding: 0">
                                                <a href="http://127.0.0.1:8000/">
                                                    <img width="20%" style="display:block; margin: 1.5% 3%; text-align: center;" src="https://aprendeayudando.herokuapp.com/static/general/images/logoTransparent.png">
                                                </a>
                                            </td>
                                        </tr>
                                        
                                        <tr>
                                            <td style="background-color: #ecf0f1">
                                                <div style="color: #34495e; margin: 4% 10% 2%; text-align: center;font-family: sans-serif">
                                                    <h2 style="color: #ff7d97; margin: 0 0 7px">¿Ha olvidado su contraseña?</h2>
                                                    <p style="margin: 2px; font-size: 15px">""" +  "Buenas, %s %s</p>" %(user.first_name, user.last_name) + """<p style="margin: 2px; font-size: 15px">
                                                        Ha solicitado una nueva contraseña en la plataforma AprendeAyudando, su nueva contraseña es: <strong>""" + "%s" %newPass + """</strong></p>
                                                    <br>
                                                    <div style="width: 100%; text-align: center">
                                                        <a style="text-decoration: none; border-radius: 5px; padding: 11px 23px; color: white; background-color: #3498db" href="http://127.0.0.1:8000/accounts/login/">Iniciar Sesión</a>	
                                                    </div>
                                                    <p style="color: #b3b3b3; font-size: 12px; text-align: center;margin: 30px 0 0">AprendeAyudando 2021</p>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>"""

                msg = EmailMultiAlternatives(subject, text_content, email_from, email_to)
                msg.attach_alternative(html_content, "text/html")
                msg.send()
                
                return render(request, template, {
                    'form': miForm,
                    'message': 'La nueva contraseña ha sido enviada a su correo electrónico.'
                })
            else:
                return render(request, template, {
                    'form': miForm,
                    'error_message': 'Inténtelo de nuevo. El correo electrónico no existe.'
                })
            

   # No post data availabe, let's just show the page.
    else:
        miForm = RecoverForm()

    return render(request, template, {'form': miForm})

@login_required
def modify(request, username):
    template = 'registration/modify.html'
    user = User.objects.get(username=username)
    if not request.user == user:
        return HttpResponseForbidden()
    modForm = UploadForm(instance=user)
    return render(request, template, {'form': modForm, 'username':username})

@login_required
def update(request, username):
    template = 'registration/modify.html'
    user = User.objects.get(username=username)
    userEmail = user.email
    modForm = UploadForm(request.POST, instance=user)
    if request.method == 'POST':
        if modForm.is_valid():

            infForm=modForm.cleaned_data
            email = infForm['email']
            password = infForm['password']
            confpassword = infForm['password_repeat']
            firstName = infForm['first_name']
            lastName = infForm['last_name']

            if User.objects.filter(email=email).exists() and userEmail != email:
                    return render(request, template, {
                        'form': modForm,
                        'error_message': 'El correo electrónico ya existe.'
                    })
            elif password != confpassword:
                    return render(request, template, {
                        'form': modForm,
                        'error_message': 'Las contraseñas no coinciden.'
                    })
            else:
                
                user.email = email
                user.first_name = firstName
                user.last_name = lastName
                
                if password != "":
                    user.set_password(password)
                    user.save()

                    subject = 'Cambio de contraseña'
                    email_from = settings.EMAIL_HOST_USER 
                    email_to = [infForm['email']]
                    text_content = "ERROR"
                    html_content = """  <table style="max-width: 600px; text-align: center; padding: 10px; margin:0 auto; border-collapse: collapse;">
                                            <tr>

AprendeAyudando/messaging/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model

# Session Handling
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseForbidden

#Models
from .models import MessagingMessage
from django.contrib.auth.models import User
from django.core.mail import send_mail

@login_required
@permission_required('messaging.view_messagingmessage', raise_exception=True)
def index(request):
    list_received_message = MessagingMessage.objects.filter(user_destination=request.user)
    list_sent_messages = MessagingMessage.objects.filter(user_origin=request.user)

    all_messages = list_received_message | list_sent_messages
    all_messages = all_messages.distinct()
    
    ctx = {
        'list_received_message':list_received_message,
        'list_sent_messages':list_sent_messages,
        'all_messages':all_messages
    }

    return render(request, 'messaging/index.html', ctx)

@login_required
@permission_required('messaging.view_messagingmessage', raise_exception=True)
def doMessage(request):

    ctx = {
        'elements':None,
        'show_email_or_user_error':False
    }

    if request.method == 'POST':
        new_message_to_email_or_username = request.POST["new_message_to_email_or_username"]
        new_message_title = request.POST["new_message_title"]
        new_message_text = request.POST["new_message_text"]
        try:
            if '@' in new_message_to_email_or_username:
                new_user_destination = User.objects.get(email=new_message_to_email_or_username)
                is_email = True
            else:
                new_user_destination = User.objects.get(username=new_message_to_email_or_username)

            mm = MessagingMessage.objects.create(
                title=new_message_title,
                text=new_message_text,
                user_origin=request.user,
                user_destination=new_user_destination
            )
            mm.save()

            subject = '{} - De: {}'.format(mm.title, request.user.username)
            message = '{} te ha mandado el siguiente mensaje:\n\n {}'.format(request.user.username, mm.text)
            email_from = 'infoaprendeayudando@gmail.com'
            email_to = [new_user_destination.email]
            send_mail(subject, message, email_from, email_to, fail_silently=True)

            return index(request)
        except User.DoesNotExist:
            elements = {
                'new_message_to_email_or_username':new_message_to_email_or_username,
                'new_message_title':new_message_title,
                'new_message_text':new_message_text
            }
            ctx['elements'] = elements
            ctx['show_email_or_user_error'] = True
            render(request, 'messaging/domessage.html', ctx)

    return render(request, 'messaging/domessage.html', ctx)

@login_required
@permission_required('messaging.view_messagingmessage', raise_exception=True)
def viewMessage(request, message_id):
    message = get_object_or_404(MessagingMessage, id=message_id)

    #------------------------CONTROL DE ACCESO-------------------
    if not message.user_destination==request.user and not message.user_origin==request.user:
        return HttpResponseForbidden()
    ctx = {
        'message':message
    }
    if request.method == 'POST':
        if not request.user == message.user_origin: 
            ctx['elements'] = {'new_message_to_email_or_username':message.user_origin}
        else:
            ctx['elements'] = {'new_message_to_email_or_username':message.user_destination}
        return render(request, 'messaging/domessage.html', ctx)
    

    return render(request, 'messaging/viewmessage.html', ctx)

AprendeAyudando/templates/activity/activity.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Actividad{% endblock %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'courses/style.css' %}">
{% endblock %}

{% block content %}
<section class="wrapper align-center login">
    

    <div class="container 100%">

        <h1>{{ activity.title }}</h1>

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    
        {% if isOwner or user.is_superuser %}
            {% if isOwner %}
                <p>Bienvenido a tu actividad: <strong>{{ activity.title }}</strong></p>
            {% else %}
                <p>Hola {{ usuario.first_name }}, te encuentras en la actividad <strong>{{ activity.title }}</strong> de la Entidad Publica/Privada <strong>{{ activity.entity.first_name }}</strong></p>
            {% endif %}
            <p>{{ activity.description }}</p>
            <a style="margin-bottom: 50px;" href="{% url 'forum:create' activity.id %}" class="button small pink">Crear un foro</a>
            {% if activity.restricted_entry %}
                <a style="margin-bottom: 50px;" href="{% url 'activity:activityrequest' activity.id %}" class="button small pink">Ver solicitudes</a>
            {% endif %}
        {% else  %}
            <p>Hola {{ usuario.first_name }}, te encuentras en la actividad: <strong>{{ activity.title }}</strong> de la Entidad Publica/Privada <strong>{{ activity.entity.first_name }}</strong></p>
            <p>{{activity.description}}</p>
        {% endif %}
            <p>Actividad restringida:
                <strong>
                    {% if activity.restricted_entry %}
                        SI
                    {% else %}
                        NO
                        {% if user.is_authenticated and not show_de_enroll and not isOwner %}
                            <form action="{% url 'activity:join' activity.id %}" method="post">
                                {% csrf_token %}
                                <input type="submit" value="Guardar Actividad">
                            </form>
                        {% endif %}
                    {% endif %}
                </strong>
            </p>
        {% if show_de_enroll %}
            {% if not activity.restricted_entry %}
                <form action="{% url 'activity:leave' activity.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Desvincular Actividad">
                </form>
            {% else %}
                <form action="{% url 'activity:leave' activity.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Desmatricularse">
                </form>
            {% endif %}
        {% endif %}

        <h4>FOROS:</h4>
        {% if forumListCourse %}
            <ol id="prettyList" style="width:92%;">
                {% for forum in forumListCourse %}
                    <li id="prettyListItem"><a href="{% url 'forum:join' forum.id %}">{{ forum.title }}</a></li>
                {% endfor %}
            </ol>
        {% else %}
            <p>Lo sentimos, no hay foros disponibles.</p>
        {% endif %}
    </div>
</section>
{% endblock %}

AprendeAyudando/templates/activity/activityrequest.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Solicitudes entrantes{% endblock %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'activity/style.css' %}">
{% endblock %}

{% block content %}
<section class="wrapper align-center login">

    <div class="container 100%">
        <h3>Solicitudes de acceso</h3>
        {% if user_list %}
        <table class="alt">
            <thead>
                <tr>
                    <th style="text-align:center;"><strong style="font-size:20px">Nombre usuario</strong></th>
                    <th style="text-align:center;"><strong style="font-size:20px">Acción</strong></th>
                </tr>
            </thead>
            <tbody>
            {% for esteUsuario in user_list %}
                <tr>
                    <td><strong>{{ esteUsuario.requester.username }}</strong></td>

                    <td style="text-align:center;">
                        <form action="{% url 'activity:action_activity_request' activity.id %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="selected_username" value="{{ esteUsuario.requester }}">
                            <ul class="actions" style="margin-top: 25px;">
                                <li>
                                    <input type="submit" value="Aceptar" name="aceptar" class="letraEnBlanco">
                                </li>
                                <li style="margin-left: 20%;">
                                    <input type="submit" value="Rechazar" name="rechazar" class="special">
                                </li>
                            </ul>
                        </form>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
            <p>No hay solicitudes de estudiantes disponibles.</p>
        {% endif %}
    </div>

</section>
{% endblock %}

AprendeAyudando/templates/activity/create.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Crear Curso{% endblock %}

{% block style %} 
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'activity/style.css' %}">
{% endblock %}

{% block content %}
    <div class="container 75% align-center minHeight">
        <h1 class="bigger">Crear actividad</h1>

        <form action="{% url 'activity:create' %}" method="POST">
            {% csrf_token %}
            <p><strong>Nombre de la actividad:</strong></p> 
            <p><input type="text" name="new_activity_name" id=""></p>
            <p><strong>Descripción:</strong></p> 
            <input type="textarea" class="biggerTextarea" name="new_activity_description" id= "">
            <p>
            <fieldset>
                <legend>Desea restringir la entrada?</legend>
                
                <input type="radio" class="eliminarDefaultCheckBox" name="is_restricted_entry" value="si" id="ssi" checked>
                <label for="ssi">
                    Sí
                </label>
                
                <input type="radio" class="eliminarDefaultCheckBox" name="is_restricted_entry" value="no" id="nno">
                <label for="nno">
                    No
                </label>
            </fieldset>
        </p>
        <input type="submit" value="Crear Actividad">
    </form>
</div>
{% endblock %}

AprendeAyudando/templates/activity/index.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Actividades disponibles{% endblock %}

{% block content %}
<section class="wrapper login">
    {% load static %}
    {% load auth_extras %}
    <link rel="stylesheet" type="text/css" href="{% static 'activity/style.css' %}">

    <div class="container 100% listaActividades">
        <div class="activityElement">
            <div class="activityElementLeft"> 
                {% if filtered_by_enrolled %}
                    <h2 class="activityTitle">Tus actividades</h2>
                {% else %}
                    <h2 class="activityTitle">Actividades disponibles</h2>
                {% endif %}
            </div>
            <div class="activityElementRight"> 
                {% if is_entity %}
                    <a style="margin-top: 25px;" href="{% url 'activity:create' %}" class="button pink">Añadir actividad</a>
                {% elif user|has_group:"Profesor" %}
                    <p>Aviso: Necesitas ser Estudiante para poder acceder a la información de las actividades restringidas.</p>
                {% elif user|is_guest %}
                    <p>Aviso: Necesitas registrarte para poder acceder a la información de los cursos.</p>
                {% endif %}
            </div>

            <div class="activityElementContent"> 
                {% if activityList %}
                <ol id="prettyList" style="width:92%;">
                    {% for activity in activityList %}
                        {% if user|is_owner:activity.entity or user|has_group:"Estudiante" or user.is_superuser or not activity.restricted_entry %}
                            <li id="prettyListItem"><a href="{% url 'activity:join' activity.id %}">{{ activity.title }}</a></li>
                        {% else %}
                            <li id="prettyListItem"><span style="color:#db685a;">{{ activity.title }}</span></li>
                        {% endif %}
                    {% endfor %}
                </ol>
                {% else %}
                    <p>Lo sentimos, no hay actividades disponibles.</p>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

AprendeAyudando/templates/activity/inscription.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Inscripción en una actividad{% endblock %}

{% block content %}
    <div class="container 125% align-center minHeight">

    {% if not user.is_authenticated %}
        <p>La actividad tiene el acceso restringido. Inicia sesión o registrate como estudiante para solicitar acceso.</p>
    {% elif not is_Estudiante_or_superuser %}
        <p>Solo los estudiantes tienen derecho al proceso de inscrición en una actividad.</p>
    {% elif exist_activity_request %}
        <p>Su solicitud ya fue enviada al dueño de la actividad.</p>
    {% else %}
        <h2>Inscripción en {{ activity.title }}</h2>
        <p> 
            La actividad tiene acceso restringido, por lo que
            necesita realizar una inscripción. Esta inscripción se enviará
            al dueño de la actividad.
        </p>
        <p>
            Desea realizar la Inscripción en la actividad <strong>{{ activity.title }}</strong>?
        </p>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <form action="{% url 'activity:inscription' activity.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Matricularse">
        </form>

    {% endif %}

    </div>
{% endblock %}