AprendeAyudando/news/urls.py
from django.urls import path
from . import views
from news.views import (NewsList, NewsCreate, NewsDetail, NewsUpdate, NewsDelete)


app_name = 'news'
urlpatterns = [
    path('', NewsList.as_view(), name='news-list'),
    path('news/add/', NewsCreate.as_view(), name='news-add'),
    path('news/<int:pk>/update/', NewsUpdate.as_view(), name='news-update'),
    path('news/<int:pk>/delete/', NewsDelete.as_view(), name='news-delete'),
    path('news/<int:pk>/', NewsDetail.as_view(), name='news-detail'),
]

AprendeAyudando/quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'
urlpatterns = [
    path('create/<str:courseOrActivity>/<int:courseOrActivity_id>/', views.createQuiz, name='createQuiz'),
    path('create/questions/<int:quiz_id>/<int:number_questions>/', views.createQuestions, name='createQuestions'),
    path('create/answers/<int:question_id>/<int:number_questions>/<int:number_answers>/', views.createAnswers, name='createAnswers'),
    path('startquiz/<int:quiz_id>/',views.startQuiz, name='startQuiz'),
    path('doquiz/<int:quiz_id>/', views.doQuiz, name='doQuiz'),
    path('doquiz/questionasked/<int:question_id>/', views.doQuizQuestionAsked, name='doQuizQuestionAsked'),
    path('deletequiz/<int:quiz_id>/', views.deleteQuiz, name='deleteQuiz'),
    path('administrationquiz/<int:quiz_id>/', views.administrationQuiz, name='administrationQuiz'),
    path('deletequestion/<int:question_id>/', views.deleteQuestion, name='deleteQuestion'),
    path('updatequestion/<int:question_id>/', views.updateQuestion, name='updateQuestion'),
    path('updateanswers/<int:question_id>/<int:number_answers>/', views.updateAnswers, name='updateAnswers'),
    path('updatequiz/<int:quiz_id>/', views.updateQuiz, name='updateQuiz'),
    path('viewqualifications/<int:quiz_id>/', views.viewQualifications, name='viewQualifications'),
]

AprendeAyudando/review/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'review'
urlpatterns = [
    path('create/<int:id_enrollable>/<str:title_enrollable>/', views.create, name='create'),
    path('list/<int:id_enrollable>/<str:title_enrollable>/<str:activityOrCourse>', views.list, name='list'),
    path('details/<int:id_review>/<str:title_enrollable>/', views.details, name='details'),
]

AprendeAyudando/urls.py
from django.contrib import admin
from django.urls import include, path

from django.contrib.auth import views as auth_views
from django.conf.urls import url

from . import views

urlpatterns = [
    path('', views.landingpage),

    url('register/', views.user_register, name='user_register'),
    url('account/', views.account, name='account'),
    url('accountdelete/', views.delete_account, name='account_delete'),
    
    path('accounts/', include('django.contrib.auth.urls')),
        # accounts/login/ [name='login']
        # accounts/logout/ [name='logout']
        # accounts/password_change/ [name='password_change']
        # accounts/password_change/done/ [name='password_change_done']
        # accounts/password_reset/ [name='password_reset']
        # accounts/password_reset/done/ [name='password_reset_done']
        # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
        # accounts/reset/done/ [name='password_reset_complete']
    
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path('courses/', include('courses.urls')),
    path('activity/', include('activity.urls')),
    path('requestpermissions/', include('request_permissions.urls')),
]

admin.site.site_header = 'Administración Aprende Ayudando'
admin.site.index_title = 'Administración'
admin.site.site_title = 'Aprende Ayudando'

activity/urls.py
from django.urls import path
from . import views

app_name = 'activity'
urlpatterns = [
    path('', views.index, name='index'), # /activity/
    path('inscription/<int:activity_id>/', views.inscription, name='inscription'), # /activity/inscripcion/1/
    path('<int:activity_id>/', views.join, name='join'), # /activity/curso/1
    path('leave/<int:activity_id>/', views.leave, name='leave'), # /activity/leave/1/
    path('create/', views.createActivity, name='create'),
    path('enrolled/', views.enrolled, name='enrolled'),
    path('<int:activity_id>/activityrequest/', views.view_activity_request, name='activityrequest'),
    path('<int:activity_id>/action_activity_request/', views.action_activity_request, name='action_activity_request'),
]

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.index, name='index'), # /courses/
    path('inscription/<int:course_id>/', views.inscription, name='inscription'), # /courses/inscription/1/
    path('<int:course_id>/', views.join, name='join'), # /courses/curso/1
    path('leave/<int:course_id>/', views.leave, name='leave'), # /courses/leave/1/
    path('create/', views.createCourse, name='create'),
    path('enrolled/', views.enrolled, name='enrolled'),

    path('createResource/<int:course_id>', views.createResource, name='createResource'),
]

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns = [
    path('create/<int:activityCourseFk>', views.createForum, name='create'),
    path('<int:forum_id>/', views.join, name='join'), # /forum/1
    path('delete/<int:forum_id>/', views.delete, name='delete'), # /forum/delete/1/

]

AprendeAyudando/news/forms.py
from django import forms
from .models import News
from django.forms import Textarea

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['headline', 'content']
        widgets = {
            'headline': forms.TextInput(attrs={'class':'form-control'}),
            'content': Textarea(attrs={'class':'form-control'})
        }

AprendeAyudando/AprendeAyudando/views.py
from django.shortcuts import render
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth import login, logout
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.core.mail import send_mail, EmailMultiAlternatives
from django.conf import settings
from .forms import RegisterForm, RecoverForm, UploadForm
import random
import string

def has_group(user, group_name):
    group = Group.objects.get(name=group_name)
    return True if group in user.groups.all() else False

def landingpage(request):
    grupo = 'Invitado'
    if request.user.has_perm('courses.view_course'):
        grupo = 'Estudiante'
    if request.user.has_perm('courses.add_course'):
        grupo = 'Profesor'
    if request.user.has_perm('activity.add_activity'):
        grupo = 'Entidad'

    context = {
        'grupo': grupo
    }
    return render(request, 'landingpage/index.html', context)

def news(request):
    return render(request, 'news/index.html')

@login_required
def account(request):
    return render(request, 'landingpage/account.html')

@login_required
def delete_account(request):
    if request.method == 'POST':
        if "cancel" in request.POST:
            return redirect('/account')
        else:
            request.user.delete()
            return redirect('/')

    return render(request, 'landingpage/delete_account.html')
    
def user_register(request):
    # if this is a POST request we need to process the form data
    template = 'registration/register.html'
   
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'El nombre de usuario ya existe.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'El correo electrónico ya existe.'
                })
            elif form.cleaned_data['password'] != form.cleaned_data['password_repeat']:
                return render(request, template, {
                    'form': form,
                    'error_message': 'Las contraseñas no coinciden.'
                })
            else:
                # Create the user:
                user = User.objects.create_user(
                    form.cleaned_data['username'],
                    form.cleaned_data['email'],
                    form.cleaned_data['password']
                )
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.save()
               
                # add role 'student' to new user
                studentGroup = Group.objects.get(name='Estudiante')
                studentGroup.user_set.add(user)

                # log the user in
                login(request, user)
               
                # redirect to accounts page
                return HttpResponseRedirect(reverse('account'))

   # No post data availabe, let's just show the page.
    else:
        form = RegisterForm()

    return render(request, template, {'form': form})

def recoverpassword(request):
    # if this is a POST request we need to process the form data
    template = 'registration/recoverpassword.html'
   
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        miForm = RecoverForm(request.POST)
        # check whether it's valid:
        if miForm.is_valid():
            if User.objects.filter(email=miForm.cleaned_data['email']).exists():
                # Minuto 19:19
                infForm=miForm.cleaned_data

                size = 12
                chars = string.ascii_uppercase+string.ascii_lowercase+string.digits

                newPass = ''.join(random.choice(chars) for x in range(size))
                
                user = User.objects.get(email=infForm['email'])
                user.set_password(newPass)
                user.save()

                subject = 'Solicitud de nueva contraseña'
                email_from = settings.EMAIL_HOST_USER 
                email_to = [infForm['email']]
                text_content = "ERROR"
                html_content = """  <table style="max-width: 600px; text-align: center; padding: 10px; margin:0 auto; border-collapse: collapse;">
                                        <tr>
                                            <td style="background-color: #ecf0f1; text-align: center; padding: 0">
                                                <a href="http://127.0.0.1:8000/">
                                                    <img width="20%" style="display:block; margin: 1.5% 3%; text-align: center;" src="https://aprendeayudando.herokuapp.com/static/general/images/logoTransparent.png">
                                                </a>
                                            </td>
                                        </tr>
                                        
                                        <tr>
                                            <td style="background-color: #ecf0f1">
                                                <div style="color: #34495e; margin: 4% 10% 2%; text-align: center;font-family: sans-serif">
                                                    <h2 style="color: #ff7d97; margin: 0 0 7px">¿Ha olvidado su contraseña?</h2>
                                                    <p style="margin: 2px; font-size: 15px">""" +  "Buenas, %s %s</p>" %(user.first_name, user.last_name) + """<p style="margin: 2px; font-size: 15px">
                                                        Ha solicitado una nueva contraseña en la plataforma AprendeAyudando, su nueva contraseña es: <strong>""" + "%s" %newPass + """</strong></p>
                                                    <br>
                                                    <div style="width: 100%; text-align: center">
                                                        <a style="text-decoration: none; border-radius: 5px; padding: 11px 23px; color: white; background-color: #3498db" href="http://127.0.0.1:8000/accounts/login/">Iniciar Sesión</a>	
                                                    </div>
                                                    <p style="color: #b3b3b3; font-size: 12px; text-align: center;margin: 30px 0 0">AprendeAyudando 2021</p>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>"""

                msg = EmailMultiAlternatives(subject, text_content, email_from, email_to)
                msg.attach_alternative(html_content, "text/html")
                msg.send()
                
                return render(request, template, {
                    'form': miForm,
                    'message': 'La nueva contraseña ha sido enviada a su correo electrónico.'
                })
            else:
                return render(request, template, {
                    'form': miForm,
                    'error_message': 'Inténtelo de nuevo. El correo electrónico no existe.'
                })
            

   # No post data availabe, let's just show the page.
    else:
        miForm = RecoverForm()

    return render(request, template, {'form': miForm})

@login_required
def modify(request, username):
    template = 'registration/modify.html'
    user = User.objects.get(username=username)
    if not request.user == user:
        return HttpResponseForbidden()
    modForm = UploadForm(instance=user)
    return render(request, template, {'form': modForm, 'username':username})

@login_required
def update(request, username):
    template = 'registration/modify.html'
    user = User.objects.get(username=username)
    userEmail = user.email
    modForm = UploadForm(request.POST, instance=user)
    if request.method == 'POST':
        if modForm.is_valid():

            infForm=modForm.cleaned_data
            email = infForm['email']
            password = infForm['password']
            confpassword = infForm['password_repeat']
            firstName = infForm['first_name']
            lastName = infForm['last_name']

            if User.objects.filter(email=email).exists() and userEmail != email:
                    return render(request, template, {
                        'form': modForm,
                        'error_message': 'El correo electrónico ya existe.'
                    })
            elif password != confpassword:
                    return render(request, template, {
                        'form': modForm,
                        'error_message': 'Las contraseñas no coinciden.'
                    })
            else:
                
                user.email = email
                user.first_name = firstName
                user.last_name = lastName
                
                if password != "":
                    user.set_password(password)
                    user.save()

                    subject = 'Cambio de contraseña'
                    email_from = settings.EMAIL_HOST_USER 
                    email_to = [infForm['email']]
                    text_content = "ERROR"
                    html_content = """  <table style="max-width: 600px; text-align: center; padding: 10px; margin:0 auto; border-collapse: collapse;">
                                            <tr>

AprendeAyudando/news/views.py
#Forms
from django.forms import ModelForm, Textarea

from .forms import NewsForm

# Models
from .models import News
from django.db import models

# Routing
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from AprendeAyudando.views import has_group

#Views
from django.views.generic import CreateView, DeleteView, UpdateView, ListView, DetailView

def tienePermisos(user):
    if has_group(user, 'Profesor') or has_group(user, 'EntidadPublicoPrivada') or user.is_superuser:
        return True
    else:
        return False

class NewsList(ListView):
    model = News
    context_object_name = 'news_list'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['isCreate'] = True
        context['tienePermisos'] = tienePermisos(self.request.user)
        context['user'] = self.request.user
        return context
    
class NewsCreate(CreateView):
    form_class = NewsForm
    model = News
    success_url = reverse_lazy('news:news-list')

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['isCreate'] = True
        context['user'] = self.request.user
        return context
    
class NewsUpdate(UpdateView):
    form_class = NewsForm
    model = News
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['isCreate'] = False
        return context
    
class NewsDelete(DeleteView):
    model = News
    success_url = reverse_lazy('news:news-list')

class NewsDetail(DetailView):
    model = News
    context_object_name = 'news'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tienePermisos'] = tienePermisos(self.request.user)
        return context

AprendeAyudando/AprendeAyudando/templates/review/create_review.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Puntuar{% endblock %}

{% block style %} 
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'activity/style.css' %}">
{% endblock %}

{% block content %}
<section class="bg-white text-dark py-5 min-vh-100">
    
    <div class="container py-5">
        {% if not success %}
            <h1>Crear Review para: {{ enrollable_title }}</h1>

            <form action="{% url 'review:create' enrollable_id enrollable_title %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="rating"><strong>Valore de 1 a 10 su experiencia en: <span class="text-secondary">{{ enrollable_title }}</span></strong></label>
                    <input class="form-control text-center col-1" type="number" max="10" min="1" name="rating" id="rating" required>
                </div>
                <div class="form-group">
                    {% if isActivity %}
                    <label for="problems"><strong>Comente posibles problemas con esta actividad:</strong></label>
                    {% else %}
                    <label for="problems"><strong>Comente posibles problemas con este curso:</strong></label>
                    {% endif %}
                    <textarea class="form-control text-center" name="problems" id= "problems" rows="3" required></textarea>
                </div>
                <div class="form-group">
                    {% if isActivity %}
                    <label for="new_activity_description"><strong>Aporta alguna posible idea para mejorar el contenido de esta actividad:</strong></strong></label>
                    {% else %}
                    <label for="problems"><strong>Comente posibles problemas con este curso:</strong></label>
                    {% endif %}
                    <textarea class="form-control text-center" name="improvements" id= "improvements" rows="3" required></textarea>
                </div>
                <input type="submit" value="Puntuar" class="btn btn-success btn-lg">
            </form>
        {% else %}
            <h1> Gracias por puntuar: <span class="text-secondary">{{ enrollable_title }}</span></h1>
            <!--btn btn-outline-dark btn-sm-->
            <a href="{% url 'account' %}" class="mr-2 btn btn-outline-dark btn-sm" style="margin-top: 10%;">Volver</a>
        {% endif %}
    </div>
</section>
{% endblock %}

AprendeAyudando/AprendeAyudando/templates/review/details.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Ver encuestas de satisfacción{% endblock %}

{% block style %} 
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'activity/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'profile/style.css' %}">
{% endblock %}

{% block content %}
<section class="bg-white text-dark py-5 min-vh-100">
    
    <div class="container py-5">
        <div class="row">
            <div class="col-12">
                <h1>Puntuación en '{{ enrollable_title }}'</h1>
            </div>
            <div class="col-12">
                <table class="table text-center">
                    <tr>
                        <th>Actividad</th>
                        <th>Usuario</th>
                        <th>Nombre completo</th>
                    </tr>
                    <tr>
                        <td>{{ enrollable_title }}</td>
                        <td>{{ review.user }}</td>
                        <td>{{ review.user.last_name }}, {{ review.user.first_name }}</td>
                    </tr>
                </table> 
            </div>
            <div class="col-12">
                <p style="margin-top: 10%"><h3>Puntuación (sobre 10):</h3><div style="border: 1px solid gray;"> {{review.rating}}</div></p>
            </div>
            <div class="col-12">
                <p><h3>Problemas encontrados:</h3><div style="border: 1px solid gray;"> {{review.problems}}</div></p>
            </div>
            <div class="col-12">
                <p><h3>Posibles mejoras:</h3><div style="border: 1px solid gray;"> {{review.improvements}}</div></p>
            </div>
        </div>
    </div>
{% endblock %}

AprendeAyudando/AprendeAyudando/templates/review/list.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Ver encuestas de satisfacción{% endblock %}

{% block style %} 
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'activity/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'profile/style.css' %}">
{% endblock %}

{% block content %}
<section class="bg-white text-dark py-5 min-vh-100">
    
    <div class="container py-5">
        <div class="row">
            <div class="col-12">
                <h1>Puntuaciones en: {{ enrollable_title }}</h1>
            </div>
            <div class="col-12">
               {% if reviews %}
                <ol id="prettyList">
                {% for review in reviews %}
                    <li id="prettyListItem"><a href="{% url 'review:details' review.id enrollable_title %}">{{ review.user }}: {{review.rating}} </a></li>
                {% endfor %}
                </ol>
                {% else %}
                    {% if isActivity %}
                    <p>Aún nadie ha puntuado esta actividad.</p>
                    {% else %}
                    <p>Aún nadie ha puntuado este curso.</p>
                    {% endif %}
                {% endif %} 
            </div>
            <div class="col-12 text-center">
                {% if isActivity %}
                    <a href="{% url 'activity:join' enrollable_id %}" class="btn btn-outline-dark btn-sm">Volver a actividad</a>  
                {% else %}
                    <a href="{% url 'courses:join' enrollable_id %}" class="btn btn-outline-dark btn-sm">Volver a curso</a>  
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}